# 12. SIGAI学习笔记
---

#### tensorflow框架

<img src="./img/全景图.png" style="width:400px">

##### Training
   - Read & Preprocess Data
   - tf.keras Estimator
   > workflow
 <img src="./img/workflow.png" style="width:400px">
     
      
##### Deployment

 1. 必学知识
 2. 选学知识
 
 ---
 
 
 

### Eager Execution
> 之前的版本tensorflow保存的是计算的流程，在建立好模型并使用Session run之后，才能输出值；Eager模式可以不用考虑run（eager 计算和定义同时完成 vs lazy 先定义后计算）





In [1]:
import tensorflow as tf
print(tf.__version__)
print(tf.executing_eagerly()) # Eager Execution ()
print(tf.keras.__version__)

2.0.0-beta1
True
2.2.4-tf


#### tensorflow numpy转换

In [2]:
import numpy as np
a = np.random.normal(size=[3,4])
b = tf.convert_to_tensor(a)
c = b.numpy()
print(c)

[[-0.28109979 -1.62704702 -1.43656204  0.62844898]
 [ 0.31583277 -0.56999273 -2.15833438  1.25290678]
 [-0.80559031  0.32686126 -1.26503973  0.87022618]]


#### Variable on GPU or CPU

In [8]:
# show device
print(b.device) # cpu


if tf.test.is_gpu_available():
    print('OK')
# 
# change to GPU
with tf.device('/device:GPU:0'):
    d = tf.convert_to_tensor([1,2])
d.device

/job:localhost/replica:0/task:0/device:CPU:0
OK


'/job:localhost/replica:0/task:0/device:CPU:0'

In [ ]:
from tensorflow.python.client import device_lib

# 列出所有的本地机器设备
local_device_protos = device_lib.list_local_devices()
# 打印
#     print(local_device_protos)

# 只打印GPU设备
[print(x) for x in local_device_protos if x.device_type == 'GPU']
